PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpedia-owl:<http://dbpedia.org/ontology/>
PREFIX dbprop:<http://dbpedia.org/property/>

SELECT * WHERE {
  ?s dbprop:birthPlace ?place .
  ?s rdf:type dbpedia-owl:Architect .
}
